### ISSUE TITLE
github.GithubException.BadCredentialsException: 401

### ISSUE THREAD

**Issue by 0m4r** [sangonzal/repository-traffic-action#17]
Hi  - starting last week I keep getting this error reported below.
I tried to re-create my token but I have not been able to sort the problem.
Any idea? Can you help?

thanks!

```
Run sangonzal/repository-traffic-action@v0.1.4
  with:
    branch: dev
  env:
    TRAFFIC_ACTION_TOKEN: ***
/usr/bin/docker run --name a33c1a32ba7c2905941738f2b48262d66ba50_246ae8 --label 8a33c1 --workdir /github/workspace --rm -e TRAFFIC_ACTION_TOKEN -e INPUT_BRANCH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/MMM-covid19/MMM-covid19":"/github/workspace" 8a33c1:a32ba7c2905941738f2b48262d66ba50
Repository name:  0m4r/_[REDACTED]_
Traceback (most recent call last):
  File "/main.py", line 9, in <module>
    repo = github.get_repo(repo_name)
  File "/root/-x-v5uFv0/lib/python3.8/site-packages/github/MainClass.py", line 345, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/root/-x-v5uFv0/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/root/-x-v5uFv0/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by 0m4r** [comment]
nevermind. I stupidly forgot to update the new token in the repository secrets.
